### PR TITLE
fix: allow connect() in dedicated method

### LINKED ISSUE #23: Should `connect()` exist as a permission on its own?
Currently, the `connect()` syscall, which is dangerous, is only allowed if we call `allow_start_tcp_clients()`. However, it seems like Unix sockets also break if this isn't allowed. 

I propose we create a separate method that just allows `connect()` and returns a `YesReally<Networking>` in order to denote its danger to the application developer, but I'd like to learn more about this design choice and any drawbacks it may have.

### PR DESCRIPTION
**Pull request by gotlougit**
Fixes #23 

Think this needs more docs.

### CODE REVIEW

File: src/builtins/network.rs [hunk 1]
```diff
@@ -201,8 +207,7 @@ impl Networking {
         self.custom.entry(Sysno::socket)
             .or_insert_with(Vec::new)
             .push(rule);
-
```
Comment (boustrophedon) [inline src/builtins/network.rs:204]: I don't think it makes sense to remove the call here since I can't imagine a case where you'd want to use this method without the connect call.

File: src/builtins/network.rs [hunk 2]
```diff
@@ -175,6 +175,12 @@ impl Networking {
         YesReally::new(self)
     }
 
+    /// Allow `connect` syscall
```
Comment (boustrophedon) [inline src/builtins/network.rs:178]: This probably needs a `# Security notes` section.

**Comment by boustrophedon** [comment]
Thanks for the PR!

File: src/builtins/network.rs (hunk 1 above)
Comment (gotlougit) [reply src/builtins/network.rs:204]: True, however this makes the code look inconsistent from when you want to only allow UDP or Unix socket access. 
I think one thing we could do is perhaps allow `connect()` in all three socket types? Then we could likely get rid of `allow_connect()`.

Comment (boustrophedon) [reply src/builtins/network.rs:204]: I probably need to refresh myself on sockets but I don't think the APIs themselves are consistent. For TCP only the client needs to connect, but for UDP and Unix sockets connect is entirely optional. In rust it will depend on what network library you're using (and possibly even your libc implementation?). So it might be fine to just add `allow_connect` and then add a note to the UDP and Unix methods that depending on your library you may need to enable connect as well.

I'm also not 100% sure on the security implications of allowing connect always. I think it's *probably* fine but I would like to maybe think about it a bit longer.

It might be good to add an example or test for this as well. E.g. "here's an example of using the raw socket/bind/listen/accept" and "here's an example of using tokio" although the existing ipc tutorials already kind of do that, though maybe not for unix sockets.

File: examples/ipc_server_with_database.rs [hunk 3]
```diff
@@ -69,6 +69,7 @@ fn run_webserver(db_socket_path: &str) {
     // extrasafe context
     SafetyContext::new()
         .enable(Networking::nothing()
+            .allow_connect().yes_really()
```
Comment (boustrophedon) [inline examples/ipc_server_with_database.rs:72]: Do the tests here actually fail without the allow_connect() here? A TCP server shouldn't need to use connect AFAIK

**Comment by boustrophedon** [comment]
Hey, sorry for not getting back to you sooner.

So I think what remains for this PR are

- Check that the examples where allow_connect was added actually require allow_connect
- Add a test showing it working (i.e. blocking an http request without allow_connect and allowing one with it, or something similar)
- Allow connect always inside `allow_start_tcp_clients`

I think it's also equally valid to do what you said in a comment and just allow connect for allow_start_unix and allow_start_udp sockets as well though. I don't see how it could be misused since you always need to be able to create the fd before connecting.

**Review by boustrophedon — APPROVED** [review]

**Comment by boustrophedon** [comment]
Sorry for the roundabout way we got to this change! Thanks for sticking with it.

Would you mind squashing everything down to 1 commit? Then I'll merge.

**Comment by gotlougit** [comment]
No problem!

**Comment by boustrophedon** [comment]
Thanks again!
